AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Data Catalog for Stock Data

Resources:
  # Glue Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: dima_database
        Description: "Glue database for stock data"

  # Glue Table for average_daily_return
  AverageDailyReturnTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref "AWS::AccountId"
      TableInput:
        Name: average_daily_return
        StorageDescriptor:
          Columns:
            - Name: date
              Type: string
            - Name: average_return
              Type: double
          Location: s3://aws-glue-stocks-assingment-dima/output/average_daily_return/
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: true
          NumberOfBuckets: -1
          StoredAsSubDirectories: false
        TableType: EXTERNAL_TABLE

  # Glue Table for average_trading_frequency
  AverageTradingFrequencyTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref "AWS::AccountId"
      TableInput:
        Name: average_trading_frequency
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: frequency
              Type: double
          Location: s3://aws-glue-stocks-assingment-dima/output/average_frequency/
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
        TableType: EXTERNAL_TABLE

  # Glue Table for stock_volatility
  StockVolatilityTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref "AWS::AccountId"
      TableInput:
        Name: stock_volatility
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: standard_deviation
              Type: double
          Location: s3://aws-glue-stocks-assingment-dima/output/volatility/
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
        TableType: EXTERNAL_TABLE

  # Glue Table for top_30_day_return_dates
  Top30DayReturnDatesTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDatabase
      CatalogId: !Ref "AWS::AccountId"
      TableInput:
        Name: top_30_day_return_dates
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: date
              Type: string
            - Name: 30_day_return
              Type: double
          Location: s3://aws-glue-stocks-assingment-dima/output/top_30_day_return_dates/
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
        TableType: EXTERNAL_TABLE

Outputs:
  GlueDatabaseName:
    Description: "Name of the Glue database"
    Value: !Ref GlueDatabase
  AverageDailyReturnTableName:
    Description: "Name of the Glue table for average_daily_return"
    Value: !Ref AverageDailyReturnTable
  AverageTradingFrequencyTableName:
    Description: "Name of the Glue table for average_trading_frequency"
    Value: !Ref AverageTradingFrequencyTable
  StockVolatilityTableName:
    Description: "Name of the Glue table for stock_volatility"
    Value: !Ref StockVolatilityTable
  Top30DayReturnDatesTableName:
    Description: "Name of the Glue table for top_30_day_return_dates"
    Value: !Ref Top30DayReturnDatesTable
